title: David Burton
email: david.p.burton@gmail.com
description: >-
  Stay a while and listen! I'm David Burton, an Irish software engineer.
  This is where I post about some of my work and what is going on in my life technology-wise.
  If there is anything on this site that interests you and you would like to know more, feel
  free to email me and I'll get back to you as soon as possible!
baseurl: ""
url: ""
twitter_username: ''
github_username:  david-p-burton

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme 
  
